services:
  db:
    image: mysql:8.0
    container_name: transandina_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  user-service:
    build: ./user-service
    container_name: user_service_app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootPassword

  route-service:
    build: ./route_service
    container_name: route_service_app
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/routes_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootPassword

  app:
    build: ./frontend-service
    container_name: welcome_app
    ports:
      - "8088:80"
    depends_on:
      - db