services:
  db:
    image: mysql:8.0
    container_name: transandina_db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootPassword"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s

  user-service:
    build: ./user-service
    container_name: user_service_app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&characterEncoding=UTF-8&useUnicode=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootPassword

  route-service:
    build: ./route_service
    container_name: route_service_app
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/routes_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&characterEncoding=UTF-8&useUnicode=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootPassword

  telemetry-service:
    build: ./telemetry-service
    container_name: telemetry_service_app
    restart: on-failure
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/telemetry_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&characterEncoding=UTF-8&useUnicode=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootPassword
      - ROUTE_SERVICE_URL=http://route-service:8081
      - ROUTE_SERVICE_USER=route
      - ROUTE_SERVICE_PASS=route123

  bff-service:
    build: ./bff-service
    container_name: bff_service_app
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - user-service
      - route-service
      - telemetry-service
    environment:
      - USER_SERVICE_URL=http://user-service:8080
      - ROUTE_SERVICE_URL=http://route-service:8081
      - TELEMETRY_SERVICE_URL=http://telemetry-service:8083

  app:
    build: ./frontend-service
    container_name: welcome_app
    ports:
      - "8088:3000"
    depends_on:
      - bff-service